import { useMemo, useState } from "react";

import {
  Link,
  useNavigate,
} from "react-router-dom";

import { useAuth } from "../context/AuthContext";

function getErrorMessage(error) {
  const response = error?.response?.data;

  if (response?.message) {
    return response.message;
  }

  if (Array.isArray(response?.errors)) {
    return response.errors
      .map((item) => item.msg || item.message)
      .filter(Boolean)
      .join(", ");
  }

  return "Could not create account. Please try again.";
}

export default function Register() {
  const { register } = useAuth();

  const navigate = useNavigate();

  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [error, setError] = useState("");
  const [submitting, setSubmitting] = useState(false);

  const validationError = useMemo(() => {
    if (!name.trim()) {
      return "Name is required.";
    }

    if (!email.trim()) {
      return "Email is required.";
    }

    if (password.length < 6) {
      return "Password must be at least 6 characters.";
    }

    if (password !== confirmPassword) {
      return "Passwords do not match.";
    }

    return "";
  }, [name, email, password, confirmPassword]);

  async function handleSubmit(e) {
    e.preventDefault();

    if (validationError) {
      setError(validationError);
      return;
    }

    try {
      setError("");
      setSubmitting(true);

      await register(name.trim(), email.trim(), password);
      navigate("/");
    } catch (err) {
      setError(getErrorMessage(err));
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <div className="auth-shell">
      <section className="auth-hero flex flex-col justify-between">
        <div>
          <div className="section-kicker">Crafted onboarding</div>
          <h1 className="display-title mt-5 max-w-xl text-5xl leading-[0.92] md:text-6xl">
            Create a fresh account without turning setup into ceremony.
          </h1>
          <p className="mt-6 max-w-xl text-base leading-7 text-[#ddcfbf]">
            Built for practical testing teams: enough structure to stay tidy,
            never so much complexity that creating or recycling users becomes a
            chore.
          </p>
        </div>

        <div className="space-y-5">
          <div className="metric-grid">
            <div className="metric-chip">
              <div className="section-kicker">Fast start</div>
              <div className="mt-3 display-title text-3xl">Minutes</div>
              <p className="mt-2 text-sm text-[#d9ccbc]">
                Spin up accounts quickly for smoke tests and repeatable flows.
              </p>
            </div>
            <div className="metric-chip">
              <div className="section-kicker">Lean scale</div>
              <div className="mt-3 display-title text-3xl">Curated</div>
              <p className="mt-2 text-sm text-[#d9ccbc]">
                Perfect for a smaller, reusable user pool with clean lifecycle
                management.
              </p>
            </div>
            <div className="metric-chip">
              <div className="section-kicker">Polished</div>
              <div className="mt-3 display-title text-3xl">Intentional</div>
              <p className="mt-2 text-sm text-[#d9ccbc]">
                Thoughtful visuals that feel product-grade, not generated by
                template.
              </p>
            </div>
          </div>
        </div>
      </section>

      <section className="auth-form-card">
        <div className="card">
          <div className="eyebrow">Create account</div>
          <h2 className="display-title mt-3 text-4xl">Join the workspace</h2>
          <p className="mt-3 text-sm leading-6 text-[#736556]">
            Start with one account now. You can keep the user pool deliberately
            small and still cover your automation scenarios well.
          </p>

          {error && (
            <div className="mt-5 rounded-[18px] border border-[rgba(168,80,63,0.18)] bg-[rgba(168,80,63,0.08)] px-4 py-3 text-sm text-[#8b4335]">
              {error}
            </div>
          )}

          <form onSubmit={handleSubmit} className="mt-6 space-y-5">
            <div>
              <label className="label">Name</label>
              <input
                className="input"
                value={name}
                autoComplete="name"
                placeholder="QA Lead"
                onChange={(e) => setName(e.target.value)}
              />
            </div>

            <div>
              <label className="label">Email</label>
              <input
                type="email"
                className="input"
                value={email}
                autoComplete="email"
                placeholder="qa@company.com"
                onChange={(e) => setEmail(e.target.value)}
              />
            </div>

            <div>
              <label className="label">Password</label>
              <input
                type="password"
                className="input"
                value={password}
                autoComplete="new-password"
                placeholder="At least 6 characters"
                onChange={(e) => setPassword(e.target.value)}
              />
            </div>

            <div>
              <label className="label">Confirm password</label>
              <input
                type="password"
                className="input"
                value={confirmPassword}
                autoComplete="new-password"
                placeholder="Repeat your password"
                onChange={(e) => setConfirmPassword(e.target.value)}
              />
            </div>

            <button className="btn w-full" disabled={submitting}>
              {submitting ? "Creating account..." : "Create premium workspace access"}
            </button>
          </form>

          <p className="mt-6 text-sm text-[#736556]">
            Already have an account?{" "}
            <Link to="/login" className="font-semibold text-[#a45b31]">
              Log in
            </Link>
          </p>
        </div>
      </section>
    </div>
  );
}
